module.exports = Object.freeze({
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  POST_USER: 'POST_USER',
  GET_ITEMS: 'GET_ITEMS',
  GET_ITEM: 'GET_ITEM',
  POST_ITEM: 'POST_ITEM',
  GET_ORDERS: 'GET_ORDERS',
  GET_ORDER: 'GET_ORDER',
  POST_ORDER: 'POST_ORDER',
});
